/**
 * Kalah
 * Kalah Game
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlayerDto { 
    gameId?: string;
    position?: PlayerDto.PositionEnum;
    token?: string;
}
export namespace PlayerDto {
    export type PositionEnum = 'One' | 'Two' | 'None';
    export const PositionEnum = {
        One: 'One' as PositionEnum,
        Two: 'Two' as PositionEnum,
        None: 'None' as PositionEnum
    };
}


