kalah:
  jwt:
    expiration: 60
    secret: oIS13005HHpKZ06bRFTCIfzYFA8eGAPhoIS13005HHpKZ06bRFTCIfzYFA8eGAPh

server:
  address: 0.0.0.0

logging:
  level:
    org:
      springframework:
        security: WARN
